### ISSUE TITLE
`current_timestamp` should be converted from `DateTimeOffset.Now` instead of `new DateTimeOffset()`

### ISSUE THREAD

**Issue by RamType0** [win7user10/Laraue.EfCoreTriggers#102]
In C# signature, `new DateTimeOffset()` returns `0001/01/01 0:00:00 +00:00`.
So,  it is not suitable for `current_timestamp` representation in C#.
It should be `DateTimeOffset.Now`!

**Comment by win7user10** [comment]
Updated that
