### ISSUE TITLE
Creating a change history/audit info in a different table

### ISSUE THREAD

**Issue by fritz-net** [win7user10/Laraue.EfCoreTriggers#19]
I really like the lib, however I ran into an Problem where I can't figure out the solution myself. I want to save all changes and also deletions to a different (audit/history)table.

I think the code should look something like this:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Balance>()
        .AfterUpdate(trigger => trigger
            .Action(action => action
                .Insert<Balance>((balanceOld, balanceNew) => balanceOld)
            )
        );
    modelBuilder.Entity<Balance>()
        .AfterDelete(trigger => trigger
            .Action(action => action
                .Insert<Balance>((balance) => balance)
            )
        );
}
```

However this would insert the Balance again in the same table causing issues with Pk. So my question is if it is somehow possible to change the target table?

One workaround in my mind is using a wrapper object, which I don't need since my Balance object already has a LastModified property.

**Comment by win7user10** [comment]
Hi, if I understood you right, you want to save data in the table with the same fields but with a different name. I think in this case you can create a model inherited from the main model
```cs
[Table("blances_logs")]
class BalanceLog : Balance
{
}
```
and then use syntax
```cs
modelBuilder.Entity<Balance>()
  .AfterDelete(trigger => trigger
    .Action(action => action
      .Insert<BalanceLog>((balance) => new BalanceLog { Field1 = balnce.Field1 })
    )
  );
```
The library now hasn't the opportunity to use one model for different tables

**Comment by fritz-net** [comment]
Thanks for your fast response. You interpreted my question correct.

Your solution seems to be the cleanest - better than changing something in the lib for an edgecase.

I tried it, however I get the following Error when creating the Migration:
`Unable to cast object of type 'System.Linq.Expressions.TypedParameterExpression' to type 'System.Linq.Expressions.MemberExpression'.`


```cs
             modelBuilder.Entity<Balance>()
                 .AfterUpdate(trigger => trigger
                     .Action(action => action
                         .Insert<BalanceHistory>((BalanceOld, BalanceNew) => new BalanceHistory(BalanceOld))
                     )
                 );
             modelBuilder.Entity<Balance>()
                 .AfterDelete(trigger => trigger
                     .Action(action => action
                         .Insert<BalanceHistory>(Balance => new BalanceHistory(Balance))
                     )
                 );
```

**Comment by fritz-net** [comment]
The issue seems to be that I can't use any objects (as properties) from the original row. So im not sure how to handle references I had to other tables before.

If I uses constants as dummy data I get:
`Unable to cast object of type 'System.Linq.Expressions.ConstantExpression' to type 'System.Linq.Expressions.ParameterExpression'.`

**Comment by fritz-net** [comment]
My current solution to get this working was implementing RawSql triggers ( https://github.com/fritz-net/Laraue.EfCoreTriggers/commit/8f977649e53268f0c10d733f103cf8ce3bddeba1 ) as described in #16

```
modelBuilder.Entity<Balance>()
.AfterDelete(trigger => trigger
    .Action(action => action
        .RawSql(@"
            EXECUTE 
            'INSERT INTO ""BalanceHistory"" '
            '('
                '""BalanceHistoryId"",'
                '""BalanceId"",'
                -- ...
                '""Reason""'
           ' ) VALUES ('
                'gen_random_uuid(),'
                '$1.""BalanceId"",'
                
                -- ...
                
                '1' -- 0=update, 1=delete
            ');'
            USING OLD
        ")
    )
);
```
