### ISSUE TITLE
DbSet<BaseEntity> should be added to the DbContext

### ISSUE THREAD

**Issue by milospantelinac** [win7user10/Laraue.EfCoreTriggers#27]
I have a problem with BaseEntity!

When I created Company I want to add a default value for Currency.
My Company Model looks this and He extends **AuditableEntityWithSoftDelete** and **AuditableEntityWithSoftDelete** extends  **BaseEntity**.

```cs
public class Company : AuditableEntityWithSoftDelete
{
    public string Name { get; set; }
    public string Email { get; set; }
    public string Website { get; set; }
    public string ContactPerson { get; set; }
    public string CustomDomain { get; set; }
    public string Logo { get; set; }
    public string LightLogo { get; set; }
    public string BrandColor { get; set; }
    public CompanyStatus Status { get; set; }
    public int PasscodeLength { get; set; }
}
```
```cs
public class AuditableEntityWithSoftDelete : BaseEntity, ISoftDelete
{
    public bool IsDeleted { get; set; }
}
```
```cs
public class BaseEntity
{
    public Guid Id { get; set; }
    public string Referral { get; set; }
}
```
I created an AfterInsert trigger.

```cs
modelBuilder.Entity<Company>()
               .AfterInsert(trigger => trigger.Action(action => action.Insert(newCompany => 
                new Currency { CompanyId = newCompany.Id, Name = "USD", Code = "USD", Prefix = "USD", TextPrefix = "USD", Suffix = "USD", TextSuffix = "USD", Delimiter = ".", Separator = ",", Decimal = 2 })));
```

When I added the Company record I want to set CompanyId in Currency table (that is FK), but Id isn't part of Company. That is part of BaseEntity, and when I put like this newCompany.Id, I get an error: **DbSet<BaseEntity> should be added to the DbContext**.

![Screenshot_7](https://user-images.githubusercontent.com/21141150/151561171-db73edf9-7f10-4152-828f-08a7cd4e526f.png)

Does anyone have any idea how to solve this?

**Comment by win7user10** [comment]
@milospantelinac, Is the currency DB set is represented in your DbContext? If it is so, I think there is a problem with retrieving metadata from the entity inherited from another entity. I now work on the library refactoring which should contain the fix for it, but don't know when will finish it

**Comment by milospantelinac** [comment]
Yeah sorry, I didn't tell you that information. But since BaseEntity is an abstract class, I only inherit it.
Great, when you add that change close this issue. That way I'll know you sent the fix. :)

**Comment by win7user10** [comment]
@milospantelinac, inheritance support was added to the library, please check it
