### ISSUE TITLE
Condition call creates wrong SQL for "=> true" for SQL Server

### ISSUE THREAD

**Issue by JarRami** [win7user10/Laraue.EfCoreTriggers#38]
If I have tables setup like this:

```
public class Project {
   [Key]
   public int ID { get; set; }
}

public class ProjectHistory{
   [Key]
   public int ID { get; set; }
   public int ProjectID { get; set; }
}
```

And I'm thinking about generating Insert, Update, Delete history from the Project table to ProjectHistory with a trigger like this:

```
modelBuilder.Entity<Project>()
	.AfterUpdate(trigger => trigger
		.Action(action => action
			.Condition((prevProject, newProject) => true)
			.Insert<ProjectHistory>((prevProject, newProject) => new ProjectHistory() {
				ProjectID = prevProject.ID,
			})
		)
	)
```

where I was thinking I'd be clever and add the Condition call immediately, being always true, so when I actually figure out a good condition, I'll remember to modify it. But this generates SQL that SQL Server doesn't accept:

```
CREATE TRIGGER LC_TRIGGER_AFTER_UPDATE_PROJECT ON Project AFTER Update AS
      BEGIN
        DECLARE @OldID INT
        DECLARE DeletedProjectCursor CURSOR FOR SELECT ID FROM Deleted
        OPEN DeletedProjectCursor
        FETCH NEXT FROM DeletedProjectCursor INTO @OldID
        WHILE @@FETCH_STATUS = 0
        BEGIN
          IF (1)
          INSERT INTO ProjectHistory ("ProjectID") SELECT @OldID;
          FETCH NEXT FROM DeletedProjectCursor INTO @OldID
        END
        CLOSE DeletedProjectCursor DEALLOCATE DeletedProjectCursor
      END
```

The offending line is the one coming from the Condition call "IF (1)" which gets an error "An expression of non-boolean type specified in a context where a condition is expected, near 'INSERT'" where as something like "IF (1=1)" would pass.

Unfortunately, I'm not able to run .NET6 so this behaviour is seen against library version 5.3.2.

**Comment by win7user10** [comment]
Hi, @JarRami, I added an exception throwing because such expressions makes no sense. It will be included in versions 5.4.x and 6.4.x
