### ISSUE TITLE
postgresql native SQL lack double quotes

### ISSUE THREAD

**Issue by innwin** [win7user10/Laraue.EfCoreTriggers#69]
version: 7.0.0-alpha

![image](https://user-images.githubusercontent.com/6335833/204126583-e0992e4b-378e-4863-bf1b-5daba6ad4afe.png)

**Comment by win7user10** [comment]
Hi, @innwin, please check the 7.0.0-alpha2 version

**Comment by innwin** [comment]
It worked very well. thx
