### ISSUE TITLE
postgresql native SQL translate error when Condition is x!=null

### ISSUE THREAD

**Issue by innwin** [win7user10/Laraue.EfCoreTriggers#71]
version: 7.0.0-alpha2

<img width="996" alt="image" src="https://user-images.githubusercontent.com/6335833/205650854-bb254c44-f7ed-410d-82b1-a8192217582b.png">

<img width="508" alt="image" src="https://user-images.githubusercontent.com/6335833/205650886-28d2ebc3-6cdb-4367-91b3-c899a38dc65e.png">

**Comment by win7user10** [comment]
Hi, it should work now
